require('./parser.js')   // session file parser
require('./utils.js')    // state managing & inspector
require('./widgets.js')  // widgets types and behaviour definition
require('./callbacks.js')// calls from mainProcess
require('./editor.js')     // ...
require('./init.js')     // ...
