[
    {
        "type": "root",
        "tabs": [
            {
                "label": "Swag-2000",
                "widgets": [
                    {
                        "type": "strip",
                        "left": 0,
                        "id": "strip_11",
                        "label": "( custom css inside ;) )",
                        "width": "100%",
                        "horizontal": true,
                        "color": "auto",
                        "css": "height:calc(100% - 70rem); --display-input:none",
                        "widgets": [
                            {
                                "type": "strip",
                                "id": "strip_1",
                                "label": "I",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "linkId": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_1",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "linkId": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_4",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_1",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_1",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_2",
                                        "height": 40,
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_1",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_1",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_9",
                                "label": "II",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_8",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_12",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_4",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_4",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_6",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_9",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_9",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_10",
                                "label": "III",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_16",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_20",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_8",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_8",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_11",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_10",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_10",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_14",
                                "label": "IV",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_24",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_28",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_12",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_12",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_14",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_11",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_11",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_15",
                                "label": "V",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_32",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_33",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_16",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_16",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_17",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_12",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_12",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_16",
                                "label": "VI",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_34",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_35",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_18",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_18",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_19",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_13",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_13",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_17",
                                "label": "VII",
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_36",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_37",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_20",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_20",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_21",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_14",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_14",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            },
                            {
                                "type": "strip",
                                "id": "strip_18",
                                "label": "VIII",
                                "horizontal": false,
                                "color": "auto",
                                "widgets": [
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_2",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_38",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "knob",
                                        "label": false,
                                        "unit": "",
                                        "height": 74,
                                        "color": "auto",
                                        "angle": 270,
                                        "css": "",
                                        "snap": false,
                                        "logScale": false,
                                        "precision": 2,
                                        "address": "/knob_3",
                                        "preArgs": [],
                                        "target": [],
                                        "range": {
                                            "min": 0,
                                            "max": 1
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "spring": false,
                                        "touchAddress": "",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "id": "knob_39",
                                        "linkId": "",
                                        "input": true
                                    },
                                    {
                                        "type": "toggle",
                                        "id": "toggle_22",
                                        "label": false,
                                        "height": 40,
                                        "color": "auto",
                                        "css": "",
                                        "on": 1,
                                        "off": 0,
                                        "value": "",
                                        "precision": 2,
                                        "address": "/toggle_22",
                                        "preArgs": [],
                                        "target": [],
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "toggle",
                                        "label": false,
                                        "color": "auto",
                                        "css": "",
                                        "value": 0,
                                        "precision": 2,
                                        "address": "/knob_1",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "id": "toggle_23",
                                        "height": 40,
                                        "linkId": "",
                                        "led": false
                                    },
                                    {
                                        "type": "fader",
                                        "id": "fader_15",
                                        "label": false,
                                        "unit": "",
                                        "alignRight": false,
                                        "horizontal": false,
                                        "compact": true,
                                        "color": "auto",
                                        "css": "flex:1",
                                        "snap": false,
                                        "range": {
                                            "min": -70,
                                            "20%": -40,
                                            "45%": -20,
                                            "60%": -10,
                                            "71%": -6,
                                            "78%": -3,
                                            "85%": 0,
                                            "92%": 3,
                                            "max": 6
                                        },
                                        "origin": "auto",
                                        "value": "",
                                        "logScale": false,
                                        "precision": 2,
                                        "meter": false,
                                        "address": "/fader_15",
                                        "preArgs": [],
                                        "target": [],
                                        "spring": false,
                                        "touchAddress": "",
                                        "meterAddress": "",
                                        "height": "auto",
                                        "pips": false,
                                        "dashed": false,
                                        "doubleTap": false,
                                        "linkId": "",
                                        "input": true
                                    }
                                ],
                                "stretch": false,
                                "variables": {},
                                "spacing": 4,
                                "_style": "style",
                                "_children": "children",
                                "width": "auto",
                                "css": "",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            }
                        ],
                        "height": "auto",
                        "top": 0,
                        "stretch": true,
                        "variables": {},
                        "_style": "style",
                        "_children": "children",
                        "spacing": 0,
                        "scroll": true,
                        "_layout": "layout",
                        "layout": "",
                        "_osc": "osc",
                        "value": "",
                        "precision": 0,
                        "address": "auto",
                        "preArgs": [],
                        "target": [],
                        "tabs": []
                    },
                    {
                        "type": "strip",
                        "top": "auto",
                        "left": 0,
                        "label": "KB",
                        "width": "100%",
                        "height": "70rem",
                        "color": "auto",
                        "css": "bottom:0",
                        "horizontal": true,
                        "widgets": [
                            {
                                "type": "xy",
                                "id": "modpad",
                                "linkId": "",
                                "label": false,
                                "width": 80,
                                "color": "auto",
                                "css": "--display-input:none;",
                                "snap": false,
                                "rangeX": {
                                    "min": 0,
                                    "50%": 0.5,
                                    "max": 1
                                },
                                "rangeY": {
                                    "min": 0,
                                    "50%": 0.5,
                                    "max": 1
                                },
                                "logScaleX": false,
                                "logScaleY": false,
                                "value": [
                                    0.5,
                                    0.5
                                ],
                                "precision": 2,
                                "address": "/mod",
                                "preArgs": [],
                                "split": false,
                                "target": [],
                                "spring": true,
                                "touchAddress": "",
                                "doubleTap": false,
                                "input": false,
                                "pips": true,
                                "pointSize": 5
                            },
                            {
                                "type": "keyboard",
                                "label": false,
                                "color": "auto",
                                "id": "keyboard",
                                "keys": 60,
                                "start": 36,
                                "traversing": true,
                                "on": 1,
                                "off": 0,
                                "precision": 2,
                                "address": "/note",
                                "preArgs": [],
                                "split": false,
                                "target": [],
                                "css": "flex:1",
                                "width": "auto"
                            },
                            {
                                "type": "strip",
                                "id": "strip_13",
                                "label": false,
                                "width": 70,
                                "horizontal": false,
                                "color": "auto",
                                "css": "",
                                "widgets": [
                                    {
                                        "type": "push",
                                        "linkId": "",
                                        "label": "^plus",
                                        "color": "auto",
                                        "css": "",
                                        "precision": 2,
                                        "address": "/octave/up",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "norelease": true,
                                        "id": "octave_up",
                                        "height": "auto"
                                    },
                                    {
                                        "type": "push",
                                        "label": "^minus",
                                        "color": "auto",
                                        "css": "",
                                        "precision": 2,
                                        "address": "/octave/down",
                                        "preArgs": [],
                                        "target": [],
                                        "on": 1,
                                        "off": 0,
                                        "linkId": "",
                                        "norelease": true,
                                        "id": "octave_down",
                                        "height": "auto"
                                    }
                                ],
                                "stretch": true,
                                "variables": {},
                                "spacing": 2,
                                "_style": "style",
                                "_children": "children",
                                "scroll": true,
                                "_layout": "layout",
                                "layout": "",
                                "_osc": "osc",
                                "value": "",
                                "precision": 0,
                                "address": "auto",
                                "preArgs": [],
                                "target": [],
                                "tabs": []
                            }
                        ],
                        "id": "strip_12",
                        "stretch": false,
                        "variables": {},
                        "spacing": 0,
                        "_style": "style",
                        "_children": "children",
                        "scroll": true,
                        "_layout": "layout",
                        "layout": "",
                        "_osc": "osc",
                        "value": "",
                        "precision": 0,
                        "address": "auto",
                        "preArgs": [],
                        "target": [],
                        "tabs": []
                    }
                ],
                "id": "tab_1",
                "type": "tab",
                "color": "auto",
                "layout": "",
                "spacing": 0,
                "value": "",
                "precision": 0,
                "address": "/tab_1",
                "preArgs": [],
                "target": [],
                "variables": "@{parent.variables}",
                "tabs": [],
                "css": "",
                "scroll": true
            }
        ],
        "color": "auto",
        "css": "",
        "value": "",
        "precision": 0,
        "address": "/swag_2000",
        "preArgs": [],
        "target": [],
        "variables": {},
        "id": "root",
        "scroll": true,
        "label": false
    }
]