[
    {
        "label": "Swag-2000",
        "widgets": [
            {
                "type": "strip",
                "left": 0,
                "id": "strip_11",
                "label": "h-strip 1",
                "width": "100%",
                "horizontal": true,
                "color": "auto",
                "css": "height:calc(100% - 100rem)",
                "widgets": [
                    {
                        "type": "strip",
                        "id": "strip_1",
                        "label": "I",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_1",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_1",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_1",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_1",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_2",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_2",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_3",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_3",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_4",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_4",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_1",
                                "label": false,
                                "unit": "",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_1",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "width": "auto",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_2",
                        "label": "II",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_5",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_5",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_3",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_3",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_6",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_6",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_7",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_7",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_8",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_8",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_2",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_2",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_3",
                        "label": "III",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_9",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_9",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_5",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_5",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_10",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_10",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_11",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_11",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_12",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_12",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_3",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_3",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_4",
                        "label": "IV",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_13",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_13",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_7",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_7",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_14",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_14",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_15",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_15",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_16",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_16",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_4",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_4",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_5",
                        "label": "V",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_17",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_17",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_9",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_9",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_18",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_18",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_19",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_19",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_20",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_20",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_5",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_5",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_6",
                        "label": "VI",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_21",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_21",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_10",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_10",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_22",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_22",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_23",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_23",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_24",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_24",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_6",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_6",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_7",
                        "label": "VII",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_25",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_25",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_13",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_13",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_26",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_26",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_27",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_27",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_28",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_28",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_7",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_7",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "height": "auto",
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_8",
                        "label": "VIII",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_29",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_29",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_15",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_15",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_30",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_30",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_31",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_31",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_32",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_32",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_8",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_8",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_9",
                        "label": "IX",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_33",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_33",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_17",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_17",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_34",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_34",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_35",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 360,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_35",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_36",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_36",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_9",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_9",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false,
                                "value": "",
                                "origin": "auto"
                            }
                        ],
                        "width": "auto"
                    },
                    {
                        "type": "strip",
                        "id": "strip_10",
                        "label": "X",
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "knob",
                                "id": "knob_37",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": 0,
                                "value": 0,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_37",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "toggle",
                                "id": "toggle_19",
                                "label": "F1",
                                "width": "auto",
                                "height": 47,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/toggle_19",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "id": "knob_38",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_38",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_39",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_39",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "knob",
                                "id": "knob_40",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": 74,
                                "color": "auto",
                                "noPip": true,
                                "compact": true,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_40",
                                "preArgs": [],
                                "target": [],
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "linkId": "",
                                "spring": false
                            },
                            {
                                "type": "fader",
                                "id": "fader_10",
                                "label": false,
                                "unit": "",
                                "width": "auto",
                                "height": "100%",
                                "alignRight": false,
                                "horizontal": false,
                                "noPip": false,
                                "compact": true,
                                "color": "auto",
                                "css": "padding:4rem",
                                "snap": false,
                                "range": {
                                    "min": -70,
                                    "20%": -40,
                                    "45%": -20,
                                    "60%": -10,
                                    "71%": -6,
                                    "78%": -3,
                                    "85%": 0,
                                    "92%": 3,
                                    "max": 6
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fader_10",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "spring": false
                            }
                        ],
                        "width": "auto"
                    }
                ],
                "height": "auto",
                "top": 0
            },
            {
                "type": "strip",
                "top": "auto",
                "left": 0,
                "label": "h-strip 2",
                "width": "100%",
                "height": "100rem",
                "color": "auto",
                "css": "bottom:0",
                "horizontal": true,
                "widgets": [
                    {
                        "type": "xy",
                        "id": "modpad",
                        "linkId": "",
                        "label": "auto",
                        "width": 96.15625,
                        "height": "auto",
                        "color": "auto",
                        "css": "--display-input:none",
                        "snap": false,
                        "rangeX": {
                            "min": 0,
                            "50%": 0.5,
                            "max": 1
                        },
                        "rangeY": {
                            "min": 0,
                            "50%": 0.5,
                            "max": 1
                        },
                        "logScaleX": false,
                        "logScaleY": false,
                        "value": [
                            0.5,
                            0.5
                        ],
                        "precision": 2,
                        "address": "/mod",
                        "preArgs": [],
                        "split": false,
                        "target": [],
                        "spring": true
                    },
                    {
                        "type": "keyboard",
                        "label": "^music",
                        "color": "auto",
                        "id": "keyboard",
                        "keys": 100,
                        "start": 36,
                        "traversing": true,
                        "on": 1,
                        "off": 0,
                        "precision": 2,
                        "address": "/note",
                        "preArgs": [],
                        "split": false,
                        "target": [],
                        "height": "auto",
                        "width": "auto",
                        "css": ""
                    },
                    {
                        "type": "strip",
                        "id": "strip_13",
                        "label": "oct.",
                        "width": 90.75,
                        "height": "auto",
                        "horizontal": false,
                        "color": "auto",
                        "css": "",
                        "widgets": [
                            {
                                "type": "push",
                                "linkId": "",
                                "label": "^plus",
                                "width": "auto",
                                "height": "50%",
                                "color": "auto",
                                "css": "",
                                "precision": 2,
                                "address": "/octave/up",
                                "preArgs": [],
                                "target": [],
                                "on": 1,
                                "off": 0,
                                "norelease": true,
                                "id": "octave_up"
                            },
                            {
                                "type": "push",
                                "label": "^minus",
                                "width": "auto",
                                "height": "50%",
                                "color": "auto",
                                "css": "",
                                "precision": 2,
                                "address": "/octave/down",
                                "preArgs": [],
                                "target": [],
                                "on": 1,
                                "off": 0,
                                "linkId": "",
                                "norelease": true,
                                "id": "octave_down"
                            }
                        ]
                    }
                ],
                "id": "strip_12"
            }
        ]
    }
]